Set up a "Hello world" project as one app with Webpack
MNisarAli/hello-rails-react pull request #1
Opened 2024-02-16 15:42 UTC by MNisarAli

## 🚀 Hello Rails React App: Initial Setup 🌐

### ♻️ Changes Made:

- [x] 🛠️ Created a new Rails app named 'hello-rails-react'.
- [x] 🛠️ Used the command `rails new -j webpack my_new_rails_app` to set up the project with webpack.
- [x] 🧰 Verified the inclusion of the `jsbundling-rails` gem in the Gemfile.
- [x] 🔄 Initialized the project with Git for version control.
- [x] 📦 Installed necessary Node dependencies for the project.
- [x] ⚙️ Created `babel.config.js` in the project root for Babel configuration.
- [x] 🔄 Updated `webpack.config.js` to include the Babel loader.
- [x] 🛢️ Set up a Postgres database for the project.

#### 🙏 Thanks for your time! Feedback and suggestions are highly appreciated.

2024-02-16 16:06 UTC, danmainah requested changes
Hi @MNisarAli , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Created a Rails API app that uses Postgresql database.
✔️ Created an API endpoint that selects a random greeting from your database messages table

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2024-02-16 16:06 UTC, danmainah commented on app/views/static/index.html.erb
> +<h1>Hello Rails React App</h1>
- [x] @MNisarAli Great work on your application, however your index page is supposed to have an empty div `\<div id="root"\></div>`, this div id is what will be used by the react app to display random greeting.

2024-02-16 16:06 UTC, danmainah commented on app/javascript/components/Greeting.js
> +};
- [ ] @MNisarAli Great work adding Greeting component, however the component is supposed to use data from our redux store to display a random greeting and not fetch the data directly, kindly consider refactoring your component
![image](https://github.com/MNisarAli/hello-rails-react/assets/61408860/2a59acc8-cfbc-4990-b706-fd8ed6176d40)

2024-02-16 16:06 UTC, danmainah commented on app/javascript/redux/reducers/greetingSlice.js
> +    const response = await fetch('/random_greeting');
- [ ] @MNisarAli Kindly check the route used to fetch random greeting , its currently wrong instead of `api/v1/greetings`, its `random_greeting`

2024-02-16 21:05 UTC, Efiamotu-1 requested changes
Hi @MNisarAli, 

![](https://camo.githubusercontent.com/a06454929d29b512682cd8b375641b59076b9e5fe1a367808e685e5bcb818de3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e32466d5957466c5a6a45794d7a49314f4455784d5455775a44686b595459355932526c4e6a4d334e7a4e6c4f574530596a4a684d695a6c634431324d563970626e526c636d35686246396e61575a7a583264705a6b6c6b4a6d4e305057632f7a3370696f6b77663057504838314d4f68752f67697068792e676966)

Great work on making the changes requested by a previous reviewer 👏 Your Code is Awesome! 💪
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-16 21:05 UTC, Efiamotu-1 commented on app/controllers/concerns/api/v1/greetings_controller.rb
- [ ] When i try to run your project locally i am getting the below errors from both the browser and from my vscode terminal, please kindly work on fixing these errors and resubmit :+1: 
![rl](https://github.com/MNisarAli/hello-rails-react/assets/89055502/222d2558-72d4-4df5-8cd6-6a8d75b8ffe1)
![lr](https://github.com/MNisarAli/hello-rails-react/assets/89055502/f90f7675-0a6c-42a3-b454-e0430951cc67)

2024-02-17 05:50 UTC, shahadat3669 approved these changes
Hi @MNisarAli, 

Your project is complete!  There is nothing else to say other than it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Highlights
✅ Project work fine without error
✅ Created an API endpoint that returns random greetings.
✅ The code is top-notch! 💯

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

 

Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadat3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-17 15:38 UTC, merged